# Generated by Django 5.1.7 on 2025-04-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='autor',
            new_name='author',
        ),
    ]
